services:
  database:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME:-nicolas}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-dev123}"
      POSTGRES_DB: "${DB_NAME:-customers}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-nicolas} -d ${DB_NAME:-dev123}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c "max_prepared_transactions=100"
  adminer:
    image: adminer
    depends_on:
      database:
        condition: service_healthy
    hostname: adminer
    container_name: adminer
    ports:
      - "8085:8080"
  redis:
    image: redis:7-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-insight:
    image: redislabs/redisinsight:latest
    depends_on:
      redis:
        condition: service_healthy
    hostname: redis-insight
    container_name: redis-insight
    ports:
      - "8001:5540"
    volumes:
      - redis-insight-data:/db
  customers:
    image: nicolasduminil/customer-api:1.0-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: customers
    container_name: customers
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresql:5432/customers
      QUARKUS_DATASOURCE_USERNAME: nicolas
      QUARKUS_DATASOURCE_PASSWORD: dev123
      DB_NAME: customers
      POSTGRES_HOST: "postgresql"
      POSTGRES_PORT: "5432"
      QUARKUS_REDIS_HOSTS: redis://redis:6379
volumes:
  redis-insight-data:
  postgres_data:
  redis_data:
