apiVersion: v1
kind: Namespace
metadata:
  name: customer-service
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: customer-service
type: Opaque
stringData:
  username: postgres
  password: ${DB_PASSWORD}  # Replace via script or use AWS Secrets Manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-api-deployment
  namespace: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service-api
  template:
    metadata:
      labels:
        app: customer-service-api
    spec:
      containers:
        - name: customer-service-api-container
          image: ${CDK_DEFAULT_ACCOUNT}.dkr.ecr.${CDK_DEFAULT_REGION}.amazonaws.com/customers-api:1.0-SNAPSHOT
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://${RDS_ENDPOINT}:5432/customers"
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: usernam
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: QUARKUS_REDIS_HOSTS
              value: "redis://${REDIS_ENDPOINT}:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-api-service
  namespace: customer-service
spec:
  selector:
    app: customer-service-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
