apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-api-deployment
  namespace: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service-api
  template:
    metadata:
      labels:
        app: customer-service-api
    spec:
      serviceAccountName: sa-customer-service
      containers:
        - name: customer-service-api-container
          image: @CDK_DEFAULT_ACCOUNT@.dkr.ecr.@CDK_DEFAULT_REGION@.amazonaws.com/@CONTAINER_IMAGE_GROUP@/@CONTAINER_IMAGE_NAME@
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-service-config
            - secretRef:
                name: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-api-service
  namespace: customer-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: customer-service-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
