apiVersion: v1
kind: Namespace
metadata:
  name: customer-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-service-sa
  namespace: customer-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-api-deployment
  namespace: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service-api
  template:
    metadata:
      labels:
        app: customer-service-api
    spec:
      containers:
        - name: customer-service-api-container
          image: @CDK_DEFAULT_ACCOUNT@.dkr.ecr.@CDK_DEFAULT_REGION@.amazonaws.com/@CONTAINER_IMAGE_GROUP@/@CONTAINER_IMAGE_NAME@
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-api-service
  namespace: customer-service
spec:
  selector:
    app: customer-service-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
